# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new214.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.winchanger = QtWidgets.QStackedWidget(self.centralwidget)
        self.winchanger.setObjectName("winchanger")
        self.page_load = QtWidgets.QWidget()
        self.page_load.setObjectName("page_load")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_load)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.project_name = QtWidgets.QLabel(self.page_load)
        self.project_name.setObjectName("project_name")
        self.gridLayout_2.addWidget(self.project_name, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.winchanger.addWidget(self.page_load)
        self.page_work = QtWidgets.QWidget()
        self.page_work.setObjectName("page_work")
        self.gridLayout = QtWidgets.QGridLayout(self.page_work)
        self.gridLayout.setObjectName("gridLayout")
        self.files_layout = QtWidgets.QGridLayout()
        self.files_layout.setObjectName("files_layout")
        self.gridLayout.addLayout(self.files_layout, 0, 0, 1, 1)
        self.winchanger.addWidget(self.page_work)
        self.quest_page = QtWidgets.QWidget()
        self.quest_page.setObjectName("quest_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.quest_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.one_label = QtWidgets.QLabel(self.quest_page)
        self.one_label.setObjectName("one_label")
        self.verticalLayout.addWidget(self.one_label)
        self.one_line = QtWidgets.QLineEdit(self.quest_page)
        self.one_line.setObjectName("one_line")
        self.verticalLayout.addWidget(self.one_line)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.winchanger.addWidget(self.quest_page)
        self.verticalLayout_2.addWidget(self.winchanger)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.winchanger.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.project_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">PROJECT_NAME</span></p></body></html>"))
        self.one_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-style:italic;\">New password</span></p></body></html>"))
