# Generated by Django 3.0.8 on 2020-07-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(default='user<3', max_length=200, verbose_name='mthod_name')),
                ('descr', models.TextField(verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('example', models.TextField(verbose_name='example')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
