# Generated by Django 3.0.8 on 2020-07-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='returns',
            field=models.TextField(default=0, verbose_name='returns'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_name',
            field=models.CharField(default='', max_length=200, verbose_name='mthod_name'),
        ),
    ]
