# Generated by Django 3.0.1 on 2020-08-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200727_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='date',
        ),
        migrations.RemoveField(
            model_name='method',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='method',
            name='description',
        ),
        migrations.RemoveField(
            model_name='method',
            name='example',
        ),
        migrations.RemoveField(
            model_name='method',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='method',
            name='returns',
        ),
    ]
