# Generated by Django 3.0.1 on 2020-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('save', models.IntegerField(verbose_name='save')),
                ('hash', models.TextField(default='0', verbose_name='hash')),
                ('bits', models.TextField(default='0', verbose_name='bits')),
            ],
        ),
    ]
