# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'locker.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Locker(object):
    def setupUi(self, Locker):
        Locker.setObjectName("Locker")
        Locker.resize(404, 102)
        self.centralwidget = QtWidgets.QWidget(Locker)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windows = QtWidgets.QStackedWidget(self.centralwidget)
        self.windows.setObjectName("windows")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QLineEdit(self.page)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.btn_enter = QtWidgets.QPushButton(self.page)
        self.btn_enter.setObjectName("btn_enter")
        self.horizontalLayout.addWidget(self.btn_enter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.text = QtWidgets.QLabel(self.frame)
        self.text.setObjectName("text")
        self.gridLayout_2.addWidget(self.text, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.windows.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.answer = QtWidgets.QLabel(self.page_2)
        self.answer.setObjectName("answer")
        self.gridLayout.addWidget(self.answer, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.windows.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.windows)
        Locker.setCentralWidget(self.centralwidget)

        self.retranslateUi(Locker)
        self.windows.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Locker)

    def retranslateUi(self, Locker):
        _translate = QtCore.QCoreApplication.translate
        Locker.setWindowTitle(_translate("Locker", "MainWindow"))
        self.btn_enter.setText(_translate("Locker", "enter"))
        self.text.setText(_translate("Locker", "succes"))
        self.answer.setText(_translate("Locker", "TextLabel"))
